apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mywp1
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.wordpress }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mywp1
  type: NodePort
status:
  loadBalancer: {}
---

apiVersion: v1
kind: service
metadata:
  name: {{ .Values.db1 }}
  labels:
    app: mydb1
    name: mydb1
spec:
  ports:
    -port: 3306
  name: mydb1
