apiVersion: v1
kind: deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.wordpress }}
  name: {{ .Values.wordpress }}
spec:
  containers:
  - image: {{ .Values.wordpress_image }}
    name: {{ .Values.wordpress }}
    env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password

    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
